name: Build and Deploy Design Tokens

on:
  push:
    paths:
      - 'tokens/**'

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # 내 컴퓨터와 똑같이 v22로 버전을 맞추고, 에러를 유발하던 cache 옵션은 삭제했습니다.
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # 안전하게 깃허브 서버에서 의존성을 직접 설치하도록 명령어를 변경했습니다.
    - name: Install dependencies
      run: npm install

    - name: Build tokens
      run: npm run build-tokens

    - name: Commit and Push compiled CSS
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@://github.com"
        
        git add dist/css/variables.css
        
        if ! git diff --cached --exit-code; then
          git commit -m "chore: 자동 생성된 디자인 토큰 CSS 반영 [skip ci]"
          git push
        else
          echo "변경 사항이 없습니다."
        fi
